[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "java -Dserver.port=$PORT -jar backend/target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

