[build]
builder = "NIXPACKS"
buildCommand = "cd backend && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -Dserver.port=$PORT -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

